### ISSUE TITLE
Why CodePointSet contain 1200 Code Points

### ISSUE THREAD

**Issue by Natai** [woxtu/NSString-RemoveEmoji#12]
Why CodePointSet contain 1200 Code Points more than 1182 in [Unicode Utilities](https://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5B%3Aemoji%3A%5D&g=emoji&i=)?

**Comment by woxtu** [comment]
I don't know why but Apple Color Emoji font seems to contain 1200 code points.
