### ISSUE TITLE
Can not detect KeyCap Sequence

### ISSUE THREAD

**Issue by Natai** [woxtu/NSString-RemoveEmoji#13]
![image](https://user-images.githubusercontent.com/10331303/45015167-6fd7fc00-b053-11e8-973e-8f024a3a9d03.png)
I think this
`let isKeycapEmoji = last == .combiningEnclosingKeycap && codepoints.contains(.variationSelector16)`
should be
`let isKeycapEmoji = last == .variationSelector16 && codepoints.contains(.combiningEnclosingKeycap)`

**Comment by woxtu** [comment]
![default](https://user-images.githubusercontent.com/5673994/45251843-f2302b00-b387-11e8-9f60-77342be26cfc.png)
You can get keycap emojis using Character Viewer.
