### ISSUE TITLE
A problem about containsEmoji

### ISSUE THREAD

**Issue by CoderMaurice** [woxtu/NSString-RemoveEmoji#14]
Hi,

when i test the code with func containsEmoji

if the first character is Emoji , it works  (like   "🧒🏻111👧🏿")
otherwise it returned an incorrect result (like  "111🧒🏻👧🏿")

i use it in my Obj-C project with Xcode9

**Comment by woxtu** [comment]
Thank you for your report. I'll check it.

**Comment by woxtu** [comment]
I finally released 1.0.7 that fixed `containsEmoji`.
