### ISSUE TITLE
Some heart emojis not recognized

### ISSUE THREAD

**Issue by ouachman** [woxtu/NSString-RemoveEmoji#17]
Hello
First of all thanks for this very useful library.
I am using the latest library and I found 3 emojis that are not recognized as emoji (maybe introduced in iOS 16?)
<img width="100" alt="Screenshot 2023-04-06 at 09 11 39" src="https://user-images.githubusercontent.com/6113079/230302288-3a02b3c5-8d19-4448-9b8b-87cb7137c66c.png">
Is there a chance to have these added to the library (along others from iOS 16 if any)
Thank you,
Eric

**Comment by woxtu** [comment]
I finally released the new version 1.5.0. Thank you for your report.
