### ISSUE TITLE
CocopodsでVer1.5.0ダウンロードできない

### ISSUE THREAD

**Issue by linxu1231** [woxtu/NSString-RemoveEmoji#18]
CocopodsでVer1.4.0はダウンロードできますが、Ver1.5.0はダンロードできません。

**Comment by woxtu** [comment]
CocoaPods support is no longer available since 1.5.0.
https://github.com/woxtu/NSString-RemoveEmoji/releases/tag/1.5.0

**Comment by linxu1231** [comment]
Thank you for your quick response!
