### ISSUE TITLE
New Emojis are not being detected

### ISSUE THREAD

**Issue by tomermobli** [woxtu/NSString-RemoveEmoji#2]

**Comment by tomermobli** [comment]
Emojis such as 🤐 were not included 
I expanded the condition so it will return YES for "codepoint <= 0x1F9C0" instead of "codepoint <= 0x1f77f"

so 
    if (0xd800 <= high && high <= 0xdbff) {
        return (0x1d000 <= codepoint && codepoint <= 0x1F9C0);
    }

**Comment by woxtu** [comment]
Thank you for your report. I'll fix it.

**Comment by woxtu** [comment]
Released 0.1.0.

**Comment by HirenOX** [comment]
Thank you..!!
