### ISSUE TITLE
An error occurs when a string contains digit

### ISSUE THREAD

**Issue by mistinka** [woxtu/NSString-RemoveEmoji#5]
XCTAssertEqual("Party Hard 0123456789".removingEmoji(), "Party Hard 0123456789")

XCTAssertEqual failed: ("Party Hard ") is not equal to ("Party Hard 0123456789")

**Comment by woxtu** [comment]
Thanks for reporting, I'll check it.

**Comment by kaylanx** [comment]
We're also having the same issue.  Numbers are being rejected.

![screen shot 2017-02-09 at 16 10 05](https://cloud.githubusercontent.com/assets/6442803/22791767/613cb2aa-eee2-11e6-85bb-2e85595b67f1.png)

**Comment by woxtu** [comment]
Hmm...

```swift
let characterSet = CharacterSet(charactersIn: "0️⃣")
"0".rangeOfCharacter(from: characterSet) // not nil
```

**Comment by nevinjethmalani** [comment]
We are also having the same problem. Did you get a chance to look at this?

**Comment by kaylanx** [comment]
We've just reverted back to 0.2.0 until it gets fixed.

**Comment by woxtu** [comment]
Sorry for delayed response. I just fixed the bug and published new version now. Try 1.0.2.
