### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by KraigWastlund** [woxtu/NSString-RemoveEmoji#7]
I would like to use your framework in my app, but we currently support tvOS and all dependencies I use must also support tvOS for my app to be Review compliant.

Can you please add tvOS support?

**Comment by woxtu** [comment]
I'll do it on the weekend.

**Comment by woxtu** [comment]
I published the new version added tvOS/watchOS support.

**Comment by KraigWastlund** [comment]
Thanks man!!
