### ISSUE TITLE
Emojis with Skin Tone Modifiers are not being detected

### ISSUE THREAD

**Issue by dandyweng** [woxtu/NSString-RemoveEmoji#8]
e.g. 👨🏾👩🏻👱🏽‍♀️👌🏼

**Comment by woxtu** [comment]
`"👨🏾".containsEmoji()` returns `true`. Could you give more information?

**Comment by dandyweng** [comment]
`NSLog(@"%@", [@"👨🏾abc" stringByRemovingEmoji]);`
returns: `🏾abc`

**Comment by woxtu** [comment]
Hmm... Unfortunately, I cannot get same result.
What's your environment?
I tested on Xcode 8.3.3 and iOS 10.2 Simulator.

**Comment by Squock** [comment]
🤣🤡🤠🤖🤓 and many other emoji

**Comment by woxtu** [comment]
@Squock Try the latest version, and please create a new issue from next time.
