### ISSUE TITLE
Doesn't recognize new emoji on iOS 11.1

### ISSUE THREAD

**Issue by marcelofabri** [woxtu/NSString-RemoveEmoji#9]
For example, 🤮.

I've tried running `./Scripts/generate.swift`, but it looks like `/System/Library/Input Methods/CharacterPalette.app/Contents/Resources/Category-Emoji.plist` doesn't exist anymore on macOS 10.13+.

**Comment by woxtu** [comment]
Thank you for your report. I'll check it on the weekend.

**Comment by domhof** [comment]
Any updates on this? I also have the same issue.

**Comment by woxtu** [comment]
Happy new year. I released 1.0.5 that added new emojis.
